"""Evaluator for the two generic 5x5 matrix invariant problem.

The evolved program returns a triple (g, f, h):

* g is an element of the algebra generated by X, Y, and real diagonal matrices.
* f(t) is a monic degree-5 polynomial function.
* h(t) is a degree-at-most-4 polynomial function.

This file implements the first three evaluation components requested by the problem:

    lambda_eval_to_zero * sum_{i=0}^4 eval_f_of_elem(f(t), h^{circ i}(g)).
    lambda_sep * sep_measure(f(t)).
    lambda_orbit_zeroes_f * extended_eval_f_of_elem(
        product_{i=0}^4 (z - h^{circ i}(t)) - f(z), g).
    lambda_not_central / (eval_f_of_elem(t - trace(g)/5, g) + epsilon).

The norm in eval_f_of_elem is the matrix 2-norm, and random specializations are
real 5-by-5 matrices.
"""

from __future__ import annotations

import importlib.util
import inspect
import math
import os
import random
import shutil
import sys
import time
import traceback
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Sequence, Tuple

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from openevolve.evaluation_result import EvaluationResult


MATRIX_SIZE = 5
F_DEGREE = 5
H_DEGREE = 4
FIRST_PART_ITERATES = 5
TOTAL_EVALUATION_PARTS = 4
STAGE1_SAMPLES = 16
STAGE2_SAMPLES = 64
RANDOM_MATRIX_SCALE = 0.35
DENOMINATOR_EPS = 1e-12
MAX_LOSS = 1e6
MONIC_TOLERANCE = 1e-6
DEFAULT_LAMBDA_EVAL_TO_ZERO = 1.0
DEFAULT_LAMBDA_SEP = 1.0
DEFAULT_LAMBDA_ORBIT_ZEROES_F = 1.0
DEFAULT_LAMBDA_NOT_CENTRAL = 1.0
DEFAULT_NOT_CENTRAL_EPSILON = 1e-6


MONIC_QUINTIC_DISCRIMINANT_TERMS: Tuple[Tuple[int, Tuple[int, int, int, int, int]], ...] = (
    (256, (5, 0, 0, 0, 3)),
    (-192, (4, 1, 0, 1, 2)),
    (-128, (4, 0, 2, 0, 2)),
    (144, (4, 0, 1, 2, 1)),
    (-27, (4, 0, 0, 4, 0)),
    (144, (3, 2, 1, 0, 2)),
    (-6, (3, 2, 0, 2, 1)),
    (-80, (3, 1, 2, 1, 1)),
    (18, (3, 1, 1, 3, 0)),
    (-1600, (3, 1, 0, 0, 3)),
    (16, (3, 0, 4, 0, 1)),
    (-4, (3, 0, 3, 2, 0)),
    (160, (3, 0, 1, 1, 2)),
    (-36, (3, 0, 0, 3, 1)),
    (-27, (2, 4, 0, 0, 2)),
    (18, (2, 3, 1, 1, 1)),
    (-4, (2, 3, 0, 3, 0)),
    (-4, (2, 2, 3, 0, 1)),
    (1, (2, 2, 2, 2, 0)),
    (1020, (2, 2, 0, 1, 2)),
    (560, (2, 1, 2, 0, 2)),
    (-746, (2, 1, 1, 2, 1)),
    (144, (2, 1, 0, 4, 0)),
    (24, (2, 0, 3, 1, 1)),
    (-6, (2, 0, 2, 3, 0)),
    (2000, (2, 0, 1, 0, 3)),
    (-50, (2, 0, 0, 2, 2)),
    (-630, (1, 3, 1, 0, 2)),
    (24, (1, 3, 0, 2, 1)),
    (356, (1, 2, 2, 1, 1)),
    (-80, (1, 2, 1, 3, 0)),
    (2250, (1, 2, 0, 0, 3)),
    (-72, (1, 1, 4, 0, 1)),
    (18, (1, 1, 3, 2, 0)),
    (-2050, (1, 1, 1, 1, 2)),
    (160, (1, 1, 0, 3, 1)),
    (-900, (1, 0, 3, 0, 2)),
    (1020, (1, 0, 2, 2, 1)),
    (-192, (1, 0, 1, 4, 0)),
    (-2500, (1, 0, 0, 1, 3)),
    (108, (0, 5, 0, 0, 2)),
    (-72, (0, 4, 1, 1, 1)),
    (16, (0, 4, 0, 3, 0)),
    (16, (0, 3, 3, 0, 1)),
    (-4, (0, 3, 2, 2, 0)),
    (-900, (0, 3, 0, 1, 2)),
    (825, (0, 2, 2, 0, 2)),
    (560, (0, 2, 1, 2, 1)),
    (-128, (0, 2, 0, 4, 0)),
    (-630, (0, 1, 3, 1, 1)),
    (144, (0, 1, 2, 3, 0)),
    (-3750, (0, 1, 1, 0, 3)),
    (2000, (0, 1, 0, 2, 2)),
    (108, (0, 0, 5, 0, 1)),
    (-27, (0, 0, 4, 2, 0)),
    (2250, (0, 0, 2, 1, 2)),
    (-1600, (0, 0, 1, 3, 1)),
    (256, (0, 0, 0, 5, 0)),
    (3125, (0, 0, 0, 0, 4)),
)


SYMBOLIC_TOOL_BINARIES: Dict[str, Tuple[str, ...]] = {
    "sage": ("sage",),
    "macaulay2": ("M2", "macaulay2"),
    "gap": ("gap",),
    "singular": ("Singular",),
    "pari_gp": ("gp",),
    "magma": ("magma",),
    "julia_oscar": ("julia",),
    "wolfram": ("wolframscript",),
}


def _available_symbolic_tools() -> Dict[str, str]:
    available = {}
    env_names = {
        "sage": "SAGE",
        "macaulay2": "M2",
        "gap": "GAP",
        "singular": "SINGULAR",
        "pari_gp": "GP",
        "magma": "MAGMA",
        "julia_oscar": "JULIA",
        "wolfram": "WOLFRAMSCRIPT",
    }
    for name, binaries in SYMBOLIC_TOOL_BINARIES.items():
        env_value = os.environ.get(env_names[name])
        if env_value:
            available[name] = env_value
            continue
        for binary in binaries:
            path = shutil.which(binary)
            if path:
                available[name] = path
                break
    return available


def _load_program(program_path: str):
    spec = importlib.util.spec_from_file_location("candidate_program", program_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load candidate program from {program_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules["candidate_program"] = module
    spec.loader.exec_module(module)
    return module


def _candidate_triple_from_program(program_path: str) -> Tuple[Any, Any, Any]:
    module = _load_program(program_path)
    for function_name in ("solve", "build_candidate", "run"):
        function = getattr(module, function_name, None)
        if callable(function):
            result = function()
            break
    else:
        raise AttributeError("Candidate program must define solve(), build_candidate(), or run().")

    if isinstance(result, dict):
        missing = [key for key in ("g", "f", "h") if key not in result]
        if missing:
            raise KeyError(f"Candidate dictionary is missing keys: {missing}")
        return result["g"], result["f"], result["h"]

    if isinstance(result, (list, tuple)) and len(result) == 3:
        return result[0], result[1], result[2]

    raise TypeError("Candidate must return a dict with keys g,f,h or a length-3 tuple.")


def _call_with_context(function: Callable, context_values: Sequence[Any]) -> Any:
    """Call a user function with as much evaluation context as it accepts."""
    try:
        signature = inspect.signature(function)
    except (TypeError, ValueError):
        signature = None

    if signature is None:
        last_error = None
        for arg_count in range(len(context_values), -1, -1):
            try:
                return function(*context_values[:arg_count])
            except TypeError as exc:
                last_error = exc
                continue
        raise TypeError(f"Could not call {function!r} with evaluator context.") from last_error

    parameters = list(signature.parameters.values())
    has_varargs = any(param.kind == inspect.Parameter.VAR_POSITIONAL for param in parameters)
    positional = [
        param
        for param in parameters
        if param.kind
        in (inspect.Parameter.POSITIONAL_ONLY, inspect.Parameter.POSITIONAL_OR_KEYWORD)
    ]
    required = [param for param in positional if param.default is inspect.Parameter.empty]

    if has_varargs:
        arg_count = len(context_values)
    else:
        arg_count = min(len(positional), len(context_values))

    if len(required) > len(context_values):
        raise TypeError(
            f"Callable requires {len(required)} positional arguments, but evaluator has "
            f"only {len(context_values)} context values."
        )

    return function(*context_values[:arg_count])


def _identity() -> np.ndarray:
    return np.eye(MATRIX_SIZE, dtype=float)


def _as_matrix(value: Any, label: str) -> np.ndarray:
    matrix = np.asarray(value, dtype=float)
    if matrix.shape != (MATRIX_SIZE, MATRIX_SIZE):
        raise ValueError(f"{label} must evaluate to a {MATRIX_SIZE}x{MATRIX_SIZE} matrix.")
    if not np.all(np.isfinite(matrix)):
        raise ValueError(f"{label} evaluated to a non-finite matrix.")
    return matrix


def _is_scalar_like(value: Any) -> bool:
    return isinstance(value, (int, float, np.number))


def _eval_scalar(spec: Any, context: Dict[str, Any]) -> float:
    x_matrix = context["x_matrix"]
    y_matrix = context["y_matrix"]
    base_value = context.get("base_value")
    current_value = context.get("current_value")

    if _is_scalar_like(spec):
        return float(spec)

    if callable(spec):
        value = _call_with_context(spec, (x_matrix, y_matrix, base_value, current_value))
        return _eval_scalar(value, context)

    if isinstance(spec, str):
        text = spec.strip()
        try:
            return float(text)
        except ValueError:
            pass
        lowered = text.lower()
        if lowered.startswith("tr(") and lowered.endswith(")"):
            return float(np.trace(_eval_element(text[3:-1], context)))
        if lowered.startswith("trace(") and lowered.endswith(")"):
            return float(np.trace(_eval_element(text[6:-1], context)))
        if text and all(letter in {"X", "Y"} for letter in text.upper()):
            return float(np.trace(_eval_word(text, x_matrix, y_matrix)))
        raise ValueError(f"Unsupported scalar string: {spec!r}")

    if isinstance(spec, dict):
        if "const" in spec:
            return _eval_scalar(spec["const"], context)
        if "scalar" in spec:
            return _eval_scalar(spec["scalar"], context)
        if "trace" in spec:
            return float(np.trace(_eval_element(spec["trace"], context)))
        if "tr" in spec:
            return float(np.trace(_eval_element(spec["tr"], context)))
        if "det" in spec:
            return float(np.linalg.det(_eval_element(spec["det"], context)))
        raise ValueError(f"Unsupported scalar dictionary keys: {sorted(spec.keys())}")

    array = np.asarray(spec)
    if array.shape == ():
        return float(array)

    raise TypeError(f"Unsupported scalar specification: {type(spec).__name__}")


def _eval_word(word: str, x_matrix: np.ndarray, y_matrix: np.ndarray) -> np.ndarray:
    result = _identity()
    for letter in word.strip().upper():
        if letter == "X":
            result = result @ x_matrix
        elif letter == "Y":
            result = result @ y_matrix
        elif letter == "Z":
            raise ValueError("Use _eval_element with context to evaluate words containing Z.")
        elif letter == "I":
            result = result @ _identity()
        else:
            raise ValueError(f"Unsupported word letter: {letter!r}")
    return result


def _eval_element(spec: Any, context: Dict[str, Any]) -> np.ndarray:
    x_matrix = context["x_matrix"]
    y_matrix = context["y_matrix"]

    if callable(spec):
        value = _call_with_context(
            spec,
            (x_matrix, y_matrix, context.get("base_value"), context.get("current_value")),
        )
        return _as_matrix(value, "callable element")

    if _is_scalar_like(spec):
        return float(spec) * _identity()

    if isinstance(spec, np.ndarray):
        return _as_matrix(spec, "array element")

    if isinstance(spec, str):
        text = spec.strip().upper()
        if text in {"", "I"}:
            return _identity()
        if text == "X":
            return x_matrix
        if text == "Y":
            return y_matrix
        if text == "Z":
            if "z_matrix" not in context:
                raise ValueError("Element string 'Z' requires a z_matrix in context.")
            return _as_matrix(context["z_matrix"], "z element")
        if all(letter in {"X", "Y", "I"} for letter in text):
            return _eval_word(text, x_matrix, y_matrix)
        if all(letter in {"X", "Y", "Z", "I"} for letter in text):
            result = _identity()
            for letter in text:
                if letter == "X":
                    result = result @ x_matrix
                elif letter == "Y":
                    result = result @ y_matrix
                elif letter == "Z":
                    if "z_matrix" not in context:
                        raise ValueError("Words containing Z require a z_matrix in context.")
                    result = result @ _as_matrix(context["z_matrix"], "z element")
                elif letter == "I":
                    result = result @ _identity()
            return result
        raise ValueError(f"Unsupported element string: {spec!r}")

    if isinstance(spec, dict):
        if "word" in spec:
            coeff = _eval_scalar(spec.get("coeff", 1.0), context)
            return coeff * _eval_word(str(spec["word"]), x_matrix, y_matrix)
        if "diag" in spec:
            values = [_eval_scalar(value, context) for value in spec["diag"]]
            if len(values) != MATRIX_SIZE:
                raise ValueError("Diagonal elements must have length 5.")
            return np.diag(values)
        if "scalar" in spec:
            return _eval_scalar(spec["scalar"], context) * _identity()
        if "sum" in spec:
            return sum((_eval_element(term, context) for term in spec["sum"]), np.zeros_like(_identity()))
        if "terms" in spec:
            return sum(
                (_eval_element(term, context) for term in spec["terms"]),
                np.zeros_like(_identity()),
            )
        if "product" in spec:
            result = _identity()
            for factor in spec["product"]:
                result = result @ _eval_element(factor, context)
            return result
        if "scale" in spec and "expr" in spec:
            return _eval_scalar(spec["scale"], context) * _eval_element(spec["expr"], context)
        if "commutator" in spec:
            left, right = spec["commutator"]
            left_value = _eval_element(left, context)
            right_value = _eval_element(right, context)
            return left_value @ right_value - right_value @ left_value
        if "power" in spec and "expr" in spec:
            exponent = int(spec["power"])
            if exponent < 0:
                raise ValueError("Negative powers are not supported for G elements.")
            return np.linalg.matrix_power(_eval_element(spec["expr"], context), exponent)
        raise ValueError(f"Unsupported element dictionary keys: {sorted(spec.keys())}")

    if isinstance(spec, (list, tuple)):
        if len(spec) == 2 and _is_scalar_like(spec[0]):
            return _eval_scalar(spec[0], context) * _eval_element(spec[1], context)
        return sum((_eval_element(term, context) for term in spec), np.zeros_like(_identity()))

    raise TypeError(f"Unsupported element specification: {type(spec).__name__}")


def _coefficients_from_spec(
    spec: Any,
    degree: int,
    context: Dict[str, Any],
    label: str,
) -> List[float]:
    x_matrix = context["x_matrix"]
    y_matrix = context["y_matrix"]
    base_value = context.get("base_value")
    current_value = context.get("current_value")

    if callable(spec):
        value = _call_with_context(spec, (x_matrix, y_matrix, base_value, current_value))
        return _coefficients_from_spec(value, degree, context, label)

    if isinstance(spec, dict):
        for key in ("coefficients", "coeffs", "poly"):
            if key in spec:
                return _coefficients_from_spec(spec[key], degree, context, label)
        if "constant" in spec:
            coeffs = [0.0] * (degree + 1)
            coeffs[-1] = _eval_scalar(spec["constant"], context)
            return coeffs
        raise ValueError(f"Unsupported {label} polynomial dictionary keys: {sorted(spec.keys())}")

    if not isinstance(spec, (list, tuple, np.ndarray)):
        raise TypeError(f"{label} polynomial must be a coefficient sequence or callable.")

    values = list(spec)
    if len(values) > degree + 1:
        raise ValueError(f"{label} polynomial has too many coefficients for degree {degree}.")
    if len(values) < degree + 1:
        values = [0.0] * (degree + 1 - len(values)) + values

    coeffs = [_eval_scalar(value, context) for value in values]
    if not all(math.isfinite(value) for value in coeffs):
        raise ValueError(f"{label} polynomial coefficients must be finite.")
    return coeffs


def _matrix_polynomial_terms(coefficients: Sequence[float], matrix: np.ndarray) -> List[np.ndarray]:
    degree = len(coefficients) - 1
    powers = [_identity()]
    for _ in range(degree):
        powers.append(powers[-1] @ matrix)
    return [float(coefficients[index]) * powers[degree - index] for index in range(degree + 1)]


def _matrix_norm(matrix: np.ndarray) -> float:
    if not np.all(np.isfinite(matrix)):
        return MAX_LOSS
    return float(np.linalg.norm(matrix, ord=2))


def _random_specializations(sample_count: int, seed: int) -> List[Tuple[np.ndarray, np.ndarray]]:
    rng = random.Random(seed)
    samples = []
    for _ in range(sample_count):
        x_matrix = np.array(
            [
                [rng.gauss(0.0, RANDOM_MATRIX_SCALE) for _ in range(MATRIX_SIZE)]
                for _ in range(MATRIX_SIZE)
            ],
            dtype=float,
        )
        y_matrix = np.array(
            [
                [rng.gauss(0.0, RANDOM_MATRIX_SCALE) for _ in range(MATRIX_SIZE)]
                for _ in range(MATRIX_SIZE)
            ],
            dtype=float,
        )
        samples.append((x_matrix, y_matrix))
    return samples


def _random_extended_specializations(
    sample_count: int,
    seed: int,
) -> List[Tuple[np.ndarray, np.ndarray, np.ndarray]]:
    rng = random.Random(seed)
    samples = []
    for _ in range(sample_count):
        matrices = []
        for _ in range(3):
            matrices.append(
                np.array(
                    [
                        [rng.gauss(0.0, RANDOM_MATRIX_SCALE) for _ in range(MATRIX_SIZE)]
                        for _ in range(MATRIX_SIZE)
                    ],
                    dtype=float,
                )
            )
        samples.append((matrices[0], matrices[1], matrices[2]))
    return samples


def _trim_scalar_poly(poly: Sequence[float], tolerance: float = 1e-14) -> List[float]:
    result = [float(value) for value in poly]
    while len(result) > 1 and abs(result[-1]) <= tolerance:
        result.pop()
    return result


def _scalar_poly_add(left: Sequence[float], right: Sequence[float]) -> List[float]:
    size = max(len(left), len(right))
    result = [0.0] * size
    for index in range(size):
        if index < len(left):
            result[index] += float(left[index])
        if index < len(right):
            result[index] += float(right[index])
    return _trim_scalar_poly(result)


def _scalar_poly_mul(left: Sequence[float], right: Sequence[float]) -> List[float]:
    result = [0.0] * (len(left) + len(right) - 1)
    for i, left_coeff in enumerate(left):
        for j, right_coeff in enumerate(right):
            result[i + j] += float(left_coeff) * float(right_coeff)
    return _trim_scalar_poly(result)


def _scalar_poly_compose(outer_low_to_high: Sequence[float], inner_low_to_high: Sequence[float]) -> List[float]:
    result = [0.0]
    power = [1.0]
    for coeff in outer_low_to_high:
        if coeff:
            result = _scalar_poly_add(result, [float(coeff) * value for value in power])
        power = _scalar_poly_mul(power, inner_low_to_high)
    return _trim_scalar_poly(result)


def _scalar_poly_eval_matrix(poly_low_to_high: Sequence[float], matrix: np.ndarray) -> np.ndarray:
    result = np.zeros_like(_identity())
    power = _identity()
    for coeff in poly_low_to_high:
        result = result + float(coeff) * power
        power = power @ matrix
    return result


def _matrix_coeff_poly_mul(left: Sequence[np.ndarray], right: Sequence[np.ndarray]) -> List[np.ndarray]:
    result = [np.zeros_like(_identity()) for _ in range(len(left) + len(right) - 1)]
    for i, left_coeff in enumerate(left):
        for j, right_coeff in enumerate(right):
            result[i + j] = result[i + j] + left_coeff @ right_coeff
    return result


def _as_coefficient_matrices(value: Any, context: Dict[str, Any]) -> List[np.ndarray]:
    if isinstance(value, dict):
        if "coefficients" in value:
            return _as_coefficient_matrices(value["coefficients"], context)
        if "coeffs" in value:
            return _as_coefficient_matrices(value["coeffs"], context)
        raise ValueError(f"Unsupported bivariate polynomial dictionary keys: {sorted(value.keys())}")

    if not isinstance(value, (list, tuple)):
        raise TypeError("Bivariate polynomial coefficients must be returned as a list or tuple.")

    return [_as_matrix(_eval_element(coefficient, context), "bivariate coefficient") for coefficient in value]


def _extended_polynomial_data(poly_spec: Any, context: Dict[str, Any]) -> Tuple[np.ndarray | None, List[np.ndarray]]:
    x_matrix = context["x_matrix"]
    y_matrix = context["y_matrix"]
    z_matrix = context["z_matrix"]
    base_value = context.get("base_value")
    current_value = context.get("current_value")

    if callable(poly_spec):
        value = _call_with_context(poly_spec, (x_matrix, y_matrix, z_matrix, base_value, current_value))
    else:
        value = poly_spec

    explicit_value = None
    if isinstance(value, dict):
        if "value" in value:
            explicit_value = _as_matrix(_eval_element(value["value"], context), "bivariate value")
        for key in ("coefficients", "coeffs"):
            if key in value:
                return explicit_value, _as_coefficient_matrices(value[key], context)
        raise ValueError(f"Unsupported bivariate polynomial dictionary keys: {sorted(value.keys())}")

    return explicit_value, _as_coefficient_matrices(value, context)


def eval_f_of_elem(
    s_coefficients: Any,
    element: Any,
    sample_count: int = STAGE2_SAMPLES,
    seed: int = 12345,
    samples: Iterable[Tuple[np.ndarray, np.ndarray]] | None = None,
    base_element: Any | None = None,
) -> float:
    """Evaluate the normalized sampled L2 error for s(element).

    For s(t)=a_0 t^5 + ... + a_5 and an element r in G, this computes

        sqrt(mean_{A,B} ( ||s(r)(A,B)|| /
             (||a_0 r^5(A,B)|| + ... + ||a_5 I||) )^2).

    Coefficients may be constants or callables evaluated at each specialization.
    """
    specializations = list(samples) if samples is not None else _random_specializations(sample_count, seed)
    if not specializations:
        raise ValueError("eval_f_of_elem requires at least one specialization.")

    squared_ratios = []
    for x_matrix, y_matrix in specializations:
        context: Dict[str, Any] = {"x_matrix": x_matrix, "y_matrix": y_matrix}
        if base_element is not None:
            context["base_value"] = _eval_element(base_element, context)

        current_value = _eval_element(element, context)
        context["current_value"] = current_value
        coefficients = _coefficients_from_spec(s_coefficients, F_DEGREE, context, "f")
        terms = _matrix_polynomial_terms(coefficients, current_value)
        numerator = _matrix_norm(sum(terms, np.zeros_like(_identity())))
        denominator = sum(_matrix_norm(term) for term in terms)

        if denominator <= DENOMINATOR_EPS:
            ratio = 0.0 if numerator <= DENOMINATOR_EPS else MAX_LOSS
        else:
            ratio = numerator / denominator
        if not math.isfinite(ratio):
            ratio = MAX_LOSS
        squared_ratios.append(min(ratio, MAX_LOSS) ** 2)

    return float(math.sqrt(sum(squared_ratios) / len(squared_ratios)))


def _monic_quintic_discriminant_terms(f_coefficients: Sequence[float]) -> List[float]:
    """Evaluate all 59 terms of the monic quintic discriminant."""
    if len(f_coefficients) != F_DEGREE + 1:
        raise ValueError("f must have exactly 6 high-to-low coefficients.")

    leading = float(f_coefficients[0])
    if abs(leading) <= DENOMINATOR_EPS:
        raise ValueError("f must have nonzero leading coefficient for discriminant normalization.")

    monic_tail = [float(value) / leading for value in f_coefficients[1:]]
    term_values = []
    for integer_coefficient, exponents in MONIC_QUINTIC_DISCRIMINANT_TERMS:
        value = float(integer_coefficient)
        try:
            for base, exponent in zip(monic_tail, exponents):
                if exponent:
                    value *= base**exponent
        except OverflowError:
            value = MAX_LOSS
        if not math.isfinite(value):
            value = math.copysign(MAX_LOSS, value)
        term_values.append(value)
    return term_values


def sep_measure(
    f_coefficients: Any,
    sample_count: int = STAGE2_SAMPLES,
    seed: int = 24680,
    samples: Iterable[Tuple[np.ndarray, np.ndarray]] | None = None,
) -> float:
    """Evaluate the normalized discriminant separation measure for f(t).

    For each specialization, the numerator is the absolute monic quintic
    discriminant. The denominator is the sum of the absolute values of the 59
    monic discriminant terms at that same specialization.
    """
    specializations = list(samples) if samples is not None else _random_specializations(sample_count, seed)
    if not specializations:
        raise ValueError("sep_measure requires at least one specialization.")

    squared_ratios = []
    for x_matrix, y_matrix in specializations:
        context: Dict[str, Any] = {"x_matrix": x_matrix, "y_matrix": y_matrix}
        coefficients = _coefficients_from_spec(f_coefficients, F_DEGREE, context, "f")
        terms = _monic_quintic_discriminant_terms(coefficients)
        numerator = abs(sum(terms))
        denominator = sum(abs(term) for term in terms)

        if denominator <= DENOMINATOR_EPS:
            ratio = 0.0 if numerator <= DENOMINATOR_EPS else MAX_LOSS
        else:
            ratio = numerator / denominator
        if not math.isfinite(ratio):
            ratio = MAX_LOSS
        squared_ratios.append(min(ratio, MAX_LOSS) ** 2)

    return float(math.sqrt(sum(squared_ratios) / len(squared_ratios)))


def extended_eval_f_of_elem(
    r_coefficients: Any,
    element: Any,
    sample_count: int = STAGE2_SAMPLES,
    seed: int = 13579,
    samples: Iterable[Tuple[np.ndarray, np.ndarray, np.ndarray]] | None = None,
) -> float:
    """Evaluate a normalized bivariate relation r(element, z).

    The input r_coefficients may be a callable returning either:
    - a list of coefficient matrices for powers of t, low-to-high, or
    - {"value": matrix, "coefficients": coefficient_matrices}.

    The denominator is the sum of matrix 2-norms of the coefficient matrices
    after X=A, Y=B, and z=C have been specialized.
    """
    specializations = (
        list(samples)
        if samples is not None
        else _random_extended_specializations(sample_count, seed)
    )
    if not specializations:
        raise ValueError("extended_eval_f_of_elem requires at least one specialization.")

    squared_ratios = []
    for x_matrix, y_matrix, z_matrix in specializations:
        context: Dict[str, Any] = {
            "x_matrix": x_matrix,
            "y_matrix": y_matrix,
            "z_matrix": z_matrix,
        }
        element_value = _eval_element(element, context)
        context["base_value"] = element_value
        context["current_value"] = element_value

        explicit_value, coefficient_matrices = _extended_polynomial_data(r_coefficients, context)
        if not coefficient_matrices:
            raise ValueError("Bivariate relation must have at least one coefficient.")

        if explicit_value is None:
            powers = [_identity()]
            for _ in range(len(coefficient_matrices) - 1):
                powers.append(powers[-1] @ element_value)
            explicit_value = sum(
                (
                    coefficient_matrices[index] @ powers[index]
                    for index in range(len(coefficient_matrices))
                ),
                np.zeros_like(_identity()),
            )

        numerator = _matrix_norm(explicit_value)
        denominator = sum(_matrix_norm(coefficient) for coefficient in coefficient_matrices)
        if denominator <= DENOMINATOR_EPS:
            ratio = 0.0 if numerator <= DENOMINATOR_EPS else MAX_LOSS
        else:
            ratio = numerator / denominator
        if not math.isfinite(ratio):
            ratio = MAX_LOSS
        squared_ratios.append(min(ratio, MAX_LOSS) ** 2)

    return float(math.sqrt(sum(squared_ratios) / len(squared_ratios)))


def _orbit_zeroes_relation(f: Any, h: Any) -> Callable:
    """Return data for product_i (z - h^i(t)) - f(z)."""

    def relation(
        x_matrix: np.ndarray,
        y_matrix: np.ndarray,
        z_matrix: np.ndarray,
        base_value: np.ndarray | None = None,
        current_value: np.ndarray | None = None,
    ) -> Dict[str, Any]:
        context: Dict[str, Any] = {
            "x_matrix": x_matrix,
            "y_matrix": y_matrix,
            "z_matrix": z_matrix,
            "base_value": base_value,
            "current_value": current_value,
        }
        if base_value is None:
            raise ValueError("Orbit relation requires the evaluated g as base_value.")

        f_coefficients = _coefficients_from_spec(f, F_DEGREE, context, "f")
        h_coefficients = _coefficients_from_spec(h, H_DEGREE, context, "h")
        h_low = [float(value) for value in reversed(h_coefficients)]

        h_iterates = []
        scalar_iterate = [0.0, 1.0]
        for _ in range(FIRST_PART_ITERATES):
            h_iterates.append(scalar_iterate)
            scalar_iterate = _scalar_poly_compose(h_low, scalar_iterate)

        product_coefficients = [_identity()]
        product_value = _identity()
        for scalar_poly in h_iterates:
            h_of_g = _scalar_poly_eval_matrix(scalar_poly, base_value)
            product_value = product_value @ (z_matrix - h_of_g)

            factor_coefficients = [z_matrix - scalar_poly[0] * _identity()]
            for coeff in scalar_poly[1:]:
                factor_coefficients.append(-float(coeff) * _identity())
            product_coefficients = _matrix_coeff_poly_mul(product_coefficients, factor_coefficients)

        f_of_z = sum(_matrix_polynomial_terms(f_coefficients, z_matrix), np.zeros_like(_identity()))
        product_value = product_value - f_of_z
        product_coefficients[0] = product_coefficients[0] - f_of_z
        return {"value": product_value, "coefficients": product_coefficients}

    return relation


def _lambda_sep_value() -> float:
    raw_value = os.environ.get("LAMBDA_SEP")
    if raw_value is None:
        return DEFAULT_LAMBDA_SEP
    try:
        value = float(raw_value)
    except ValueError:
        return DEFAULT_LAMBDA_SEP
    if not math.isfinite(value):
        return DEFAULT_LAMBDA_SEP
    return max(0.0, value)


def _lambda_orbit_zeroes_f_value() -> float:
    raw_value = os.environ.get("LAMBDA_ORBIT_ZEROES_F")
    if raw_value is None:
        return DEFAULT_LAMBDA_ORBIT_ZEROES_F
    try:
        value = float(raw_value)
    except ValueError:
        return DEFAULT_LAMBDA_ORBIT_ZEROES_F
    if not math.isfinite(value):
        return DEFAULT_LAMBDA_ORBIT_ZEROES_F
    return max(0.0, value)


def _lambda_not_central_value() -> float:
    raw_value = os.environ.get("LAMBDA_NOT_CENTRAL")
    if raw_value is None:
        return DEFAULT_LAMBDA_NOT_CENTRAL
    try:
        value = float(raw_value)
    except ValueError:
        return DEFAULT_LAMBDA_NOT_CENTRAL
    if not math.isfinite(value):
        return DEFAULT_LAMBDA_NOT_CENTRAL
    return max(0.0, value)


def _not_central_epsilon_value() -> float:
    raw_value = os.environ.get("NOT_CENTRAL_EPSILON")
    if raw_value is None:
        return DEFAULT_NOT_CENTRAL_EPSILON
    try:
        value = float(raw_value)
    except ValueError:
        return DEFAULT_NOT_CENTRAL_EPSILON
    if not math.isfinite(value):
        return DEFAULT_NOT_CENTRAL_EPSILON
    return max(0.0, value)


def _lambda_eval_to_zero_value() -> float:
    raw_value = os.environ.get("LAMBDA_EVAL_TO_ZERO")
    if raw_value is None:
        return DEFAULT_LAMBDA_EVAL_TO_ZERO
    try:
        value = float(raw_value)
    except ValueError:
        return DEFAULT_LAMBDA_EVAL_TO_ZERO
    if not math.isfinite(value):
        return DEFAULT_LAMBDA_EVAL_TO_ZERO
    return max(0.0, value)


def _not_central_polynomial(g: Any) -> Callable:
    """Return coefficients for t - trace(g)/5."""

    def coefficients(
        x_matrix: np.ndarray,
        y_matrix: np.ndarray,
        base_value: np.ndarray | None = None,
        current_value: np.ndarray | None = None,
    ) -> List[float]:
        context: Dict[str, Any] = {"x_matrix": x_matrix, "y_matrix": y_matrix}
        g_value = base_value if base_value is not None else _eval_element(g, context)
        return [1.0, -float(np.trace(g_value)) / MATRIX_SIZE]

    return coefficients


def _h_iterate_element(g: Any, h: Any, iteration: int) -> Callable:
    def evaluate(
        x_matrix: np.ndarray,
        y_matrix: np.ndarray,
        base_value: np.ndarray | None = None,
        current_value: np.ndarray | None = None,
    ) -> np.ndarray:
        context: Dict[str, Any] = {"x_matrix": x_matrix, "y_matrix": y_matrix}
        value = _eval_element(g, context)
        context["base_value"] = value
        context["current_value"] = value
        h_coefficients = _coefficients_from_spec(h, H_DEGREE, context, "h")
        for _ in range(iteration):
            value = sum(_matrix_polynomial_terms(h_coefficients, value), np.zeros_like(_identity()))
            if not np.all(np.isfinite(value)):
                raise ValueError("h-iterate produced a non-finite matrix.")
            context["current_value"] = value
        return value

    return evaluate


def _candidate_complexity(g: Any, f: Any, h: Any) -> float:
    return float(len(repr(g)) + len(repr(f)) + len(repr(h)))


def _characteristic_polynomial_of_element(element: Any) -> Callable:
    """Return high-to-low coefficients of det(tI - element)."""

    def coefficients(
        x_matrix: np.ndarray,
        y_matrix: np.ndarray,
        base_value: np.ndarray | None = None,
        current_value: np.ndarray | None = None,
    ) -> List[float]:
        context: Dict[str, Any] = {"x_matrix": x_matrix, "y_matrix": y_matrix}
        if base_value is not None:
            matrix = base_value
        elif current_value is not None:
            matrix = current_value
        else:
            matrix = _eval_element(element, context)
        coeffs = np.poly(matrix)
        coeffs = np.real_if_close(coeffs, tol=1000)
        return [float(np.real(coefficient)) for coefficient in coeffs]

    return coefficients


def _polynomial_validation_metrics(g: Any, f: Any, h: Any) -> Dict[str, float]:
    samples = _random_specializations(3, 91_337)
    monic_errors = []
    h_leading_abs = []
    for x_matrix, y_matrix in samples:
        context: Dict[str, Any] = {"x_matrix": x_matrix, "y_matrix": y_matrix}
        context["base_value"] = _eval_element(g, context)
        context["current_value"] = context["base_value"]
        f_coeffs = _coefficients_from_spec(f, F_DEGREE, context, "f")
        h_coeffs = _coefficients_from_spec(h, H_DEGREE, context, "h")
        monic_errors.append(abs(f_coeffs[0] - 1.0))
        h_leading_abs.append(abs(h_coeffs[0]))
    return {
        "monic_error": float(max(monic_errors)),
        "h_leading_abs": float(max(h_leading_abs)),
    }


def _first_part_loss(
    g: Any,
    f: Any,
    h: Any,
    sample_count: int,
    seed: int,
) -> Tuple[float, List[float]]:
    values = []
    for iteration in range(FIRST_PART_ITERATES):
        element = _h_iterate_element(g, h, iteration)
        values.append(
            eval_f_of_elem(
                f,
                element,
                sample_count=sample_count,
                seed=seed + 10_000 * iteration,
                base_element=g,
            )
        )
    return float(sum(values)), values


def _score_from_objective_loss(objective_loss: float, monic_error: float, complexity: float) -> float:
    if not math.isfinite(objective_loss):
        return 0.0
    monic_penalty = 1.0 / (1.0 + 1000.0 * max(0.0, monic_error - MONIC_TOLERANCE))
    complexity_penalty = 1.0 / (1.0 + max(0.0, complexity - 4000.0) / 4000.0)
    return float((1.0 / (1.0 + max(0.0, objective_loss))) * monic_penalty * complexity_penalty)


def _evaluate(program_path: str, sample_count: int, seed: int, stage_name: str) -> EvaluationResult:
    started = time.time()
    tools = _available_symbolic_tools()
    try:
        g, f, h = _candidate_triple_from_program(program_path)
        f = _characteristic_polynomial_of_element(g)
        validation = _polynomial_validation_metrics(g, f, h)
        first_part_loss, first_part_terms = _first_part_loss(g, f, h, sample_count, seed)
        separation_measure = sep_measure(f, sample_count=sample_count, seed=seed + 50_000)
        orbit_zeroes_measure = extended_eval_f_of_elem(
            _orbit_zeroes_relation(f, h),
            g,
            sample_count=sample_count,
            seed=seed + 90_000,
        )
        not_central_measure = eval_f_of_elem(
            _not_central_polynomial(g),
            g,
            sample_count=sample_count,
            seed=seed + 130_000,
            base_element=g,
        )
        lambda_eval_to_zero = _lambda_eval_to_zero_value()
        lambda_sep = _lambda_sep_value()
        lambda_orbit_zeroes_f = _lambda_orbit_zeroes_f_value()
        lambda_not_central = _lambda_not_central_value()
        not_central_epsilon = _not_central_epsilon_value()
        eval_to_zero_loss = lambda_eval_to_zero * first_part_loss
        sep_loss = lambda_sep * separation_measure
        orbit_zeroes_f_loss = lambda_orbit_zeroes_f * orbit_zeroes_measure
        not_central_loss = lambda_not_central / (not_central_measure + not_central_epsilon)
        objective_loss = eval_to_zero_loss + sep_loss + orbit_zeroes_f_loss + not_central_loss
        elapsed = time.time() - started
        complexity = _candidate_complexity(g, f, h)
        combined_score = _score_from_objective_loss(
            objective_loss,
            validation["monic_error"],
            complexity,
        )

        metrics = {
            "combined_score": combined_score,
            "objective_loss": float(objective_loss),
            "first_part_loss": float(first_part_loss),
            "first_part_score": float(1.0 / (1.0 + max(0.0, first_part_loss))),
            "eval_to_zero_loss": float(eval_to_zero_loss),
            "lambda_eval_to_zero": float(lambda_eval_to_zero),
            "sep_measure": float(separation_measure),
            "sep_loss": float(sep_loss),
            "lambda_sep": float(lambda_sep),
            "orbit_zeroes_measure": float(orbit_zeroes_measure),
            "orbit_zeroes_f_loss": float(orbit_zeroes_f_loss),
            "lambda_orbit_zeroes_f": float(lambda_orbit_zeroes_f),
            "not_central_measure": float(not_central_measure),
            "not_central_loss": float(not_central_loss),
            "lambda_not_central": float(lambda_not_central),
            "not_central_epsilon": float(not_central_epsilon),
            "implemented_parts": 4.0,
            "total_parts": float(TOTAL_EVALUATION_PARTS),
            "monic_error": validation["monic_error"],
            "h_leading_abs": validation["h_leading_abs"],
            "candidate_complexity": complexity,
            "eval_time": float(elapsed),
        }
        artifacts = {
            "stage": stage_name,
            "first_part_terms": ", ".join(f"{value:.6e}" for value in first_part_terms),
            "eval_to_zero_loss": f"{eval_to_zero_loss:.6e}",
            "lambda_eval_to_zero": str(lambda_eval_to_zero),
            "lambda_eval_to_zero_hint": (
                "Set environment variable LAMBDA_EVAL_TO_ZERO to change this weight."
            ),
            "sep_measure": f"{separation_measure:.6e}",
            "sep_formula": (
                "sqrt(mean((abs(discriminant(f)) / "
                "sum(abs(each of the 59 monic discriminant terms)))^2))"
            ),
            "discriminant_term_count": str(len(MONIC_QUINTIC_DISCRIMINANT_TERMS)),
            "lambda_sep": str(lambda_sep),
            "lambda_sep_hint": "Set environment variable LAMBDA_SEP to change this weight.",
            "orbit_zeroes_measure": f"{orbit_zeroes_measure:.6e}",
            "orbit_zeroes_formula": (
                "extended_eval_f_of_elem(product_{i=0}^4 "
                "(z - h^{circ i}(t)) - f(z), g)"
            ),
            "orbit_zeroes_f_loss": f"{orbit_zeroes_f_loss:.6e}",
            "lambda_orbit_zeroes_f": str(lambda_orbit_zeroes_f),
            "lambda_orbit_zeroes_f_hint": (
                "Set environment variable LAMBDA_ORBIT_ZEROES_F to change this weight."
            ),
            "not_central_measure": f"{not_central_measure:.6e}",
            "not_central_formula": (
                "lambda_not_central / "
                "(eval_f_of_elem(t - trace(g)/5, g) + epsilon)"
            ),
            "not_central_loss": f"{not_central_loss:.6e}",
            "lambda_not_central": str(lambda_not_central),
            "lambda_not_central_hint": (
                "Set environment variable LAMBDA_NOT_CENTRAL to change this weight."
            ),
            "not_central_epsilon": str(not_central_epsilon),
            "not_central_epsilon_hint": (
                "Set environment variable NOT_CENTRAL_EPSILON to change epsilon."
            ),
            "formula": (
                "lambda_eval_to_zero * "
                "sum_{i=0}^4 eval_f_of_elem(f(t), h^{circ i}(g))"
            ),
            "objective_formula": "part1 + part2 + part3 + part4",
            "implemented_parts": f"4/{TOTAL_EVALUATION_PARTS}",
            "norm": "matrix 2-norm",
            "sample_count": str(sample_count),
            "available_symbolic_tools": str(tools),
            "tool_usage_hint": (
                "The seed program exposes available_symbolic_tools() and "
                "run_symbolic_tool(name, script) for Sage, Macaulay2, GAP, Singular, "
                "PARI/GP, Magma, Julia/Oscar, and WolframScript when installed."
            ),
        }
        if validation["monic_error"] > MONIC_TOLERANCE:
            artifacts["monic_hint"] = (
                "f(t) should be monic of degree 5; the leading coefficient should "
                "evaluate to 1 at random specializations."
            )
        artifacts["next_parts"] = "All four requested objective parts are implemented."
        return EvaluationResult(metrics=metrics, artifacts=artifacts)
    except Exception as exc:
        return EvaluationResult(
            metrics={
                "combined_score": 0.0,
                "objective_loss": MAX_LOSS,
                "first_part_loss": MAX_LOSS,
                "first_part_score": 0.0,
                "eval_to_zero_loss": MAX_LOSS,
                "lambda_eval_to_zero": _lambda_eval_to_zero_value(),
                "sep_measure": MAX_LOSS,
                "sep_loss": MAX_LOSS,
                "lambda_sep": _lambda_sep_value(),
                "orbit_zeroes_measure": MAX_LOSS,
                "orbit_zeroes_f_loss": MAX_LOSS,
                "lambda_orbit_zeroes_f": _lambda_orbit_zeroes_f_value(),
                "not_central_measure": 0.0,
                "not_central_loss": MAX_LOSS,
                "lambda_not_central": _lambda_not_central_value(),
                "not_central_epsilon": _not_central_epsilon_value(),
                "implemented_parts": 4.0,
                "total_parts": float(TOTAL_EVALUATION_PARTS),
                "monic_error": MAX_LOSS,
                "candidate_complexity": 0.0,
                "error": 0.0,
            },
            artifacts={
                "failure_stage": stage_name,
                "error_type": type(exc).__name__,
                "error_message": str(exc),
                "traceback": traceback.format_exc(),
                "available_symbolic_tools": str(tools),
            },
        )


def evaluate_stage1(program_path: str) -> EvaluationResult:
    return _evaluate(program_path, STAGE1_SAMPLES, 12_345, "stage1")


def evaluate_stage2(program_path: str) -> EvaluationResult:
    return _evaluate(program_path, STAGE2_SAMPLES, 67_890, "stage2")


def evaluate(program_path: str) -> EvaluationResult:
    return evaluate_stage2(program_path)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python evaluator.py path/to/program.py")
        raise SystemExit(2)
    result = evaluate(sys.argv[1])
    print(result.metrics)
    print(result.artifacts)
