"""Seed program for the two 5x5 generic matrix invariant problem.

The evolved code should return three objects:

1. g, an element of the algebra generated by X, Y, and real diagonal matrices.
2. f(t), a monic degree-5 polynomial function.
3. h(t), a degree-at-most-4 polynomial function.

The evaluator samples real 5-by-5 matrices A, B and evaluates these objects
numerically. Polynomial coefficients may be constants or callables depending on
the sampled X=A, Y=B.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from typing import Callable, Dict, Optional

import numpy as np


MatrixFunction = Callable[[np.ndarray, np.ndarray], np.ndarray]
CoefficientFunction = Callable[[np.ndarray, np.ndarray, np.ndarray], list[float]]


@dataclass(frozen=True)
class SymbolicTool:
    """Description of an external symbolic algebra command."""

    binaries: tuple[str, ...]
    env_var: str
    mode: str
    args: tuple[str, ...] = ()
    suffix: str = ".txt"


SYMBOLIC_TOOLS: Dict[str, SymbolicTool] = {
    "sage": SymbolicTool(("sage",), "SAGE", "arg", ("-c",), ".sage.py"),
    "macaulay2": SymbolicTool(("M2", "macaulay2"), "M2", "file", ("--script",), ".m2"),
    "gap": SymbolicTool(("gap",), "GAP", "stdin", ("-q",), ".g"),
    "singular": SymbolicTool(("Singular",), "SINGULAR", "file", ("--no-rc", "--quiet"), ".sing"),
    "pari_gp": SymbolicTool(("gp",), "GP", "stdin", ("-q",), ".gp"),
    "magma": SymbolicTool(("magma",), "MAGMA", "file", ("-b",), ".magma"),
    "julia_oscar": SymbolicTool(("julia",), "JULIA", "file", ("--startup-file=no",), ".jl"),
    "wolfram": SymbolicTool(("wolframscript",), "WOLFRAMSCRIPT", "arg", ("-code",), ".wl"),
}


def _resolve_tool(tool_name: str) -> Optional[str]:
    """Return an executable path for a symbolic tool, if one is available."""
    spec = SYMBOLIC_TOOLS[tool_name]
    env_path = os.environ.get(spec.env_var)
    if env_path:
        return env_path
    for binary in spec.binaries:
        found = shutil.which(binary)
        if found:
            return found
    return None


def available_symbolic_tools() -> Dict[str, Optional[str]]:
    """Report symbolic math systems visible to this evaluator process."""
    return {name: _resolve_tool(name) for name in SYMBOLIC_TOOLS}


def run_symbolic_tool(tool_name: str, script: str, timeout: int = 30) -> subprocess.CompletedProcess:
    """Run a symbolic algebra script with Sage, Macaulay2, GAP, Singular, etc.

    The evaluator does not require these tools, but the OpenEvolve agents may use
    them when installed. Commands can also be supplied with environment variables
    such as SAGE, M2, GAP, SINGULAR, GP, MAGMA, JULIA, and WOLFRAMSCRIPT.
    """
    if tool_name not in SYMBOLIC_TOOLS:
        raise ValueError(f"Unknown symbolic tool: {tool_name}")

    executable = _resolve_tool(tool_name)
    if not executable:
        raise RuntimeError(
            f"{tool_name} is not available. Installed tools: {available_symbolic_tools()}"
        )

    spec = SYMBOLIC_TOOLS[tool_name]
    if spec.mode == "arg":
        return subprocess.run(
            [executable, *spec.args, script],
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
        )

    if spec.mode == "stdin":
        return subprocess.run(
            [executable, *spec.args],
            input=script,
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
        )

    if spec.mode == "file":
        temp_path = None
        try:
            with tempfile.NamedTemporaryFile("w", suffix=spec.suffix, delete=False) as handle:
                handle.write(script)
                temp_path = handle.name
            return subprocess.run(
                [executable, *spec.args, temp_path],
                text=True,
                capture_output=True,
                timeout=timeout,
                check=False,
            )
        finally:
            if temp_path and os.path.exists(temp_path):
                os.unlink(temp_path)

    raise RuntimeError(f"Unsupported tool mode for {tool_name}: {spec.mode}")


def word_element(word: str) -> MatrixFunction:
    """Build the element of G represented by a word in X and Y."""

    def evaluate(x_matrix: np.ndarray, y_matrix: np.ndarray) -> np.ndarray:
        result = np.eye(x_matrix.shape[0])
        for letter in word.upper():
            if letter == "X":
                result = result @ x_matrix
            elif letter == "Y":
                result = result @ y_matrix
            else:
                raise ValueError(f"Unsupported word letter: {letter}")
        return result

    return evaluate


def characteristic_polynomial_of_g(g: MatrixFunction) -> CoefficientFunction:
    """Return high-to-low coefficients of det(tI-g), evaluated at a sample."""

    def coefficients(
        x_matrix: np.ndarray,
        y_matrix: np.ndarray,
        g_value: np.ndarray | None = None,
    ) -> list[float]:
        matrix = g_value if g_value is not None else g(x_matrix, y_matrix)
        coeffs = np.poly(matrix)
        coeffs = np.real_if_close(coeffs, tol=1000)
        return [float(np.real(c)) for c in coeffs]

    return coefficients


# EVOLVE-BLOCK-START
_RANDOM_SEED = 20260625
_EXPONENTIAL_SCALE = 0.08
_EXPONENTIAL_TERMS = 18
_RNG = np.random.default_rng(_RANDOM_SEED)
_RANDOM_DIAGONAL = tuple(float(value) for value in _RNG.uniform(0.75, 1.35, size=5))
_CENTRAL_FEATURE_COUNT = 8
_F_RANDOM_WEIGHTS = _RNG.normal(0.0, 1.0, size=(5, _CENTRAL_FEATURE_COUNT))
_H_RANDOM_WEIGHTS = _RNG.normal(0.0, 1.0, size=(5, _CENTRAL_FEATURE_COUNT))


def _constant_diagonal(values: tuple[float, float, float, float, float]) -> np.ndarray:
    """Return a real diagonal generator of G."""
    return np.diag(np.array(values, dtype=float))


def _matrix_exponential_taylor(matrix: np.ndarray) -> np.ndarray:
    """Approximate exp(matrix) by a finite Taylor polynomial."""
    identity = np.eye(matrix.shape[0], dtype=float)
    result = identity.copy()
    term = identity.copy()
    for degree in range(1, _EXPONENTIAL_TERMS + 1):
        term = term @ matrix / float(degree)
        result = result + term
    return result


def _exponential_diagonal_generator() -> MatrixFunction:
    diagonal = _constant_diagonal(_RANDOM_DIAGONAL)

    def evaluate(x_matrix: np.ndarray, y_matrix: np.ndarray) -> np.ndarray:
        exponent = _EXPONENTIAL_SCALE * (x_matrix - y_matrix)
        return diagonal @ _matrix_exponential_taylor(exponent)

    return evaluate


def _central_trace_features(x_matrix: np.ndarray, y_matrix: np.ndarray) -> np.ndarray:
    """Trace-word invariants used as random central scalar coefficients."""
    delta = x_matrix - y_matrix
    commutator = x_matrix @ y_matrix - y_matrix @ x_matrix
    size = float(x_matrix.shape[0])
    return np.array(
        [
            1.0,
            float(np.trace(x_matrix)) / size,
            float(np.trace(y_matrix)) / size,
            float(np.trace(x_matrix @ y_matrix)) / size,
            float(np.trace(x_matrix @ x_matrix)) / size,
            float(np.trace(y_matrix @ y_matrix)) / size,
            float(np.trace(delta @ delta)) / size,
            float(np.trace(commutator @ commutator)) / size,
        ],
        dtype=float,
    )


def _random_central_coefficients(
    weights: np.ndarray,
    scale: float,
) -> CoefficientFunction:
    def coefficients(
        x_matrix: np.ndarray,
        y_matrix: np.ndarray,
        g_value: np.ndarray | None = None,
    ) -> list[float]:
        del g_value
        features = _central_trace_features(x_matrix, y_matrix)
        values = scale * (weights @ features)
        return [float(value) for value in values]

    return coefficients


def random_monic_central_quintic() -> CoefficientFunction:
    central_tail = _random_central_coefficients(_F_RANDOM_WEIGHTS, scale=0.12)

    def coefficients(
        x_matrix: np.ndarray,
        y_matrix: np.ndarray,
        g_value: np.ndarray | None = None,
    ) -> list[float]:
        return [1.0, *central_tail(x_matrix, y_matrix, g_value)]

    return coefficients


def random_central_quartic() -> CoefficientFunction:
    return _random_central_coefficients(_H_RANDOM_WEIGHTS, scale=0.08)


def build_candidate() -> dict:
    """Return random central-polynomial data around D*exp(c*(X-Y))."""

    g = _exponential_diagonal_generator()
    f = random_monic_central_quintic()
    h = random_central_quartic()
    return {"g": g, "f": f, "h": h}
# EVOLVE-BLOCK-END


def solve() -> dict:
    """OpenEvolve evaluator entry point."""
    return build_candidate()


if __name__ == "__main__":
    candidate = solve()
    print("candidate keys:", sorted(candidate.keys()))
    print("symbolic tools:", available_symbolic_tools())
